"""empty message

Revision ID: 24727390349d
Revises: f1f152b07cbd
Create Date: 2025-05-20 20:04:04.489189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24727390349d'
down_revision = 'f1f152b07cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=False),
    sa.Column('option_v', sa.String(length=100), nullable=False),
    sa.Column('option_a', sa.String(length=120), nullable=False),
    sa.Column('option_k', sa.String(length=120), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order'),
    sa.UniqueConstraint('question')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('rol', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dominant_channel', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('canales')
    op.drop_table('user')
    op.drop_table('test')
    op.drop_table('recomendacion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recomendacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('visual', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('auditivo', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('kinestesico', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='recomendacion_pkey')
    )
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pregunta', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('respuesta_1', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('respuesta_2', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('respuesta_3', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('respuesta_1_canal', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('respuesta_2_canal', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('respuesta_3_canal', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('resultado_test', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('apellido', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('rol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_name', name='user_user_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('canales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('visual', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('auditivo', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('kinestesico', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='canales_pkey')
    )
    op.drop_table('user_answers')
    op.drop_table('test_results')
    op.drop_table('users')
    op.drop_table('questions')
    # ### end Alembic commands ###
