"""empty message

Revision ID: 44f833072d45
Revises: 52f045bd0013
Create Date: 2025-05-29 05:33:17.516708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f833072d45'
down_revision = '52f045bd0013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_results', sa.String(length=120), nullable=True))
        batch_op.drop_column('test_result')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_result', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
        batch_op.drop_column('test_results')

    # ### end Alembic commands ###
