"""empty message

Revision ID: 52f045bd0013
Revises: 24727390349d
Create Date: 2025-05-28 23:15:46.221970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52f045bd0013'
down_revision = '24727390349d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answers')
    op.drop_table('test_results')
    op.drop_table('questions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_result', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('test_result')

    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('questions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('option_v', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('option_a', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('option_k', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='questions_pkey'),
    sa.UniqueConstraint('order', name='questions_order_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('question', name='questions_question_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('test_results',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('test_results_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dominant_channel', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='test_results_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='test_results_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_result_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selected_option', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('user_answers_question_id_fkey')),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], name=op.f('user_answers_test_result_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_answers_pkey'))
    )
    # ### end Alembic commands ###
