"""empty message

Revision ID: 85f965229d29
Revises: bd18d5e52e4d
Create Date: 2025-06-04 16:21:17.184971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f965229d29'
down_revision = 'bd18d5e52e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_channel', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('learning_channel')

    # ### end Alembic commands ###
