"""empty message

Revision ID: bd18d5e52e4d
Revises: 44f7db14b14f
Create Date: 2025-06-04 16:02:45.554126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd18d5e52e4d'
down_revision = '44f7db14b14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('learning_channel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_channel', sa.VARCHAR(length=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
