"""empty message

Revision ID: f1f152b07cbd
Revises: 7c8d80b62213
Create Date: 2025-05-17 02:21:17.470169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f152b07cbd'
down_revision = '7c8d80b62213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visual', sa.String(length=30), nullable=False),
    sa.Column('auditivo', sa.String(length=30), nullable=False),
    sa.Column('kinestesico', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recomendacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visual', sa.String(length=500), nullable=False),
    sa.Column('auditivo', sa.String(length=500), nullable=False),
    sa.Column('kinestesico', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.String(length=500), nullable=False),
    sa.Column('respuesta_1', sa.String(length=500), nullable=False),
    sa.Column('respuesta_2', sa.String(length=500), nullable=False),
    sa.Column('respuesta_3', sa.String(length=500), nullable=False),
    sa.Column('respuesta_1_canal', sa.String(length=30), nullable=False),
    sa.Column('respuesta_2_canal', sa.String(length=30), nullable=False),
    sa.Column('respuesta_3_canal', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('resultado_test', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nombre', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('apellido', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('rol', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint(None, ['user_name'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('rol')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')
        batch_op.drop_column('resultado_test')
        batch_op.drop_column('user_name')

    op.drop_table('test')
    op.drop_table('recomendacion')
    op.drop_table('canales')
    # ### end Alembic commands ###
